osx_image: xcode9.0
language: objective-c

cache: cocoapods
podfile: Podfile

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod update
  - pod install

script:
  - set -o pipefail
  - xcodebuild -workspace Findme.xcworkspace -scheme Findme -destination "OS=10.3.1,name=iPhone SE" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty

after_success:
  - sleep 3